from . import product_template
from . import product_brand
from . import product_property
from . import product_category
from . import product_property
from . import product_template
from . import res_partner
from . import stock_warehouse
from . import res_partner
from . import sale_order
